CONFIG = {
    "PERCENTAGE_BEFORE_BAR": False,
    "UPDATE_FETCHER_EVERY_X_SECONDS": 0,
    "UPDATE_DISPLAY_EVERY_X_SECONDS": 1 / 60,
    "DEBUG": False,
    "TITLE": "Dashboard",
    "LOGGING": False,
    "ONLY_FETCH_ON_TASK_MANAGER": False,
}


TEXT_HEIGHT = 16
TEXT_WIDTH = TEXT_HEIGHT / 1.6

HALF_TEXT_HEIGHT = TEXT_HEIGHT / 2
QUARTER_TEXT_HEIGHT = TEXT_HEIGHT / 4

INITIAL_TAB = "task"
# INITIAL_TAB = "file"

SCREEN_WIDTH, SCREEN_HEIGHT = 600, 400

FITTING_TEXT_WIDTH, FITTING_TEXT_HEIGHT = int(SCREEN_WIDTH / TEXT_WIDTH), int(
    SCREEN_HEIGHT / TEXT_HEIGHT
)

FOOTER_SIZE = 4 * TEXT_HEIGHT

DRAWING_AREA_BOTTOM = SCREEN_HEIGHT - FOOTER_SIZE + TEXT_HEIGHT
DRAWING_AREA_TOP = TEXT_HEIGHT * 2 + HALF_TEXT_HEIGHT
DRAWING_AREA_SIZE = DRAWING_AREA_BOTTOM - DRAWING_AREA_TOP
